import React from 'react';
import useEscapeKey from '../hooks/useEscapeKey.ts';
import { CloseIcon } from './Icons.tsx';

interface TermsModalProps {
  isOpen: boolean;
  onAccept: () => void;
  onDecline: () => void;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onAccept, onDecline, onClose }) => {
  useEscapeKey(onClose);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={onClose} role="dialog" aria-modal="true">
      <div 
        className="bg-gradient-to-br from-nexus-surface-800 to-nexus-primary-800 border border-nexus-border-medium rounded-xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        <header className="p-4 flex justify-between items-center border-b border-nexus-border-medium flex-shrink-0">
          <h2 className="text-xl font-bold text-nexus-text-primary">Terms & Conditions: BW Nexus AI Platform Agreement</h2>
          <button onClick={onClose} className="p-1 text-nexus-text-secondary hover:text-white" title="Close"><CloseIcon className="w-6 h-6"/></button>
        </header>

        <main className="flex-grow p-6 overflow-y-auto max-w-none text-sm leading-relaxed">
            <div className="space-y-6">
                <div>
                    <h3 className="text-lg font-bold text-nexus-text-primary mb-3">Terms & Conditions: BW Nexus AI Platform Agreement</h3>
                    <p className="text-nexus-text-secondary mb-4">Welcome to BW Nexus AI. By clicking "Accept and Continue," you agree to be bound by the following terms and conditions. Please read them carefully.</p>
                </div>

                <div>
                    <h4 className="font-bold text-nexus-text-primary mb-2">1. Service Description</h4>
                    <p className="text-nexus-text-secondary mb-3">The BW Nexus AI platform provides AI-powered intelligence, analysis, and report generation services for regional development and strategic partnership identification. The service is provided "as-is" and is intended for guidance and decision-support only.</p>
                </div>

                <div>
                    <h4 className="font-bold text-nexus-text-primary mb-2">2. User Responsibilities</h4>
                    <p className="text-nexus-text-secondary mb-3">You are responsible for the accuracy of the information you provide and for independently verifying any information generated by the system before making strategic or financial commitments. You agree not to use the service for any unlawful purpose.</p>
                </div>

                <div>
                    <h4 className="font-bold text-nexus-text-primary mb-2">3. Data and Privacy</h4>
                    <p className="text-nexus-text-secondary mb-3">We are committed to protecting your privacy. Information you provide is used solely for the purpose of generating your requested reports and improving our services. We do not sell your data to third parties. Please refer to our full Privacy Policy for more details.</p>
                </div>

                <div>
                    <h4 className="font-bold text-nexus-text-primary mb-2">4. Intellectual Property</h4>
                    <p className="text-nexus-text-secondary mb-3">The reports and content generated for you are for your internal use. The underlying technology, proprietary models (including but not limited to RROI, TPT, SEAM), and the BW Nexus AI platform itself are the exclusive intellectual property of BW Global Advisory.</p>
                </div>

                <div>
                    <h4 className="font-bold text-nexus-text-primary mb-2">5. Limitation of Liability</h4>
                    <p className="text-nexus-text-secondary mb-3">BW Global Advisory makes no warranties as to the absolute completeness or accuracy of the AI-generated content. In no event shall BW Global Advisory be liable for any direct, indirect, incidental, or consequential damages arising out of the use of or inability to use the service.</p>
                </div>

                <div className="border-t border-nexus-border-medium pt-4">
                    <h3 className="text-lg font-bold text-nexus-text-primary mb-3">How to Use BW Nexus AI</h3>
                    <p className="text-nexus-text-secondary mb-4">You are about to use a powerful system designed to unlock the hidden potential of global regions. This is not a simple search engine. You are about to begin a structured, 12-step intelligence-gathering process guided by our AI co-pilot.</p>

                    <h4 className="font-bold text-nexus-text-primary mb-3">Your Journey: The 12-Step Intelligence Framework</h4>

                    <div className="space-y-4 mb-4">
                        <div>
                            <h5 className="font-semibold text-nexus-accent-cyan mb-1">Phase 1: Scope & Context (Steps 1-3)</h5>
                            <p className="text-nexus-text-secondary text-sm">You will define <strong>who you are</strong> (your persona), <strong>where you are looking</strong> (your target region), and <strong>what you want to achieve</strong> (your core objective). This is the most critical phase, as it creates the "brief" for our AI.</p>
                        </div>

                        <div>
                            <h5 className="font-semibold text-nexus-accent-cyan mb-1">Phase 2: Analysis & Strategy (Steps 4-6)</h5>
                            <p className="text-nexus-text-secondary text-sm">You will configure your <strong>AI analysis team</strong> and run advanced diagnostics. This includes conducting due diligence, assessing risk, and exploring a curated dashboard of potential partners.</p>
                        </div>

                        <div>
                            <h5 className="font-semibold text-nexus-accent-cyan mb-1">Phase 3: Execution & Planning (Steps 7-9)</h5>
                            <p className="text-nexus-text-secondary text-sm">You will move from analysis to action. Here, you will use tools to forecast growth, model stakeholder perspectives, and build a framework for creating strong relationships.</p>
                        </div>

                        <div>
                            <h5 className="font-semibold text-nexus-accent-cyan mb-1">Phase 4: Finalization & Generation (Steps 10-12)</h5>
                            <p className="text-nexus-text-secondary text-sm">You will assess the long-term viability of your strategy, review all your inputs, and, with a final click, instruct the multi-agent AI system to <strong>synthesize all 12 steps into a comprehensive Intelligence Blueprint.</strong></p>
                        </div>
                    </div>

                    <div className="bg-nexus-surface-700 p-3 rounded-lg mb-4">
                        <h5 className="font-semibold text-nexus-text-primary mb-2">The Outcome: A Partnership Toolkit</h5>
                        <p className="text-nexus-text-secondary text-sm">At the end of this process, you will receive a world-class intelligence report and a professionally drafted outreach letter—a complete toolkit designed to help you start confident, data-driven conversations.</p>
                    </div>
                </div>

                <div className="border-t border-nexus-border-medium pt-4">
                    <h4 className="font-bold text-nexus-text-primary mb-2">Additional Terms</h4>
                    <ul className="text-nexus-text-secondary text-sm space-y-1 mb-4">
                        <li>• You are responsible for ensuring compliance with applicable laws and regulations.</li>
                        <li>• BWGA reserves the right to monitor usage and terminate access if terms are violated.</li>
                        <li>• Any engagement for commissioned reports will be formalized through separate service agreements.</li>
                        <li>• All sensitive information shared with BWGA will be treated with utmost confidentiality.</li>
                        <li>• This service provides AI-generated analysis for informational purposes only.</li>
                        <li>• Content does not constitute financial, legal, or investment advice.</li>
                    </ul>
                </div>

                <div className="border-t border-nexus-border-medium pt-4">
                    <p className="text-nexus-text-secondary font-medium">By accepting, you acknowledge that you have read, understood, and agree to these terms.</p>
                </div>
            </div>
        </main>

        <footer className="p-4 border-t border-nexus-border-medium flex-shrink-0 flex justify-end items-center gap-4">
            <button onClick={onDecline} className="nexus-button-secondary">Decline</button>
            <button onClick={onAccept} className="nexus-button-primary">Accept</button>
        </footer>
      </div>
    </div>
  );
};