import React from 'react';
import useEscapeKey from '../hooks/useEscapeKey.ts';
import { CloseIcon } from './Icons.tsx';

interface TermsModalProps {
  isOpen: boolean;
  onAccept: () => void;
  onDecline: () => void;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onAccept, onDecline, onClose }) => {
  useEscapeKey(onClose);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={onClose} role="dialog" aria-modal="true">
      <div 
        className="bg-gradient-to-br from-nexus-surface-800 to-nexus-primary-800 border border-nexus-border-medium rounded-xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        <header className="p-4 flex justify-between items-center border-b border-nexus-border-medium flex-shrink-0">
          <h2 className="text-xl font-bold text-nexus-text-primary">Terms & Conditions: BW Nexus AI Platform Agreement</h2>
          <button onClick={onClose} className="p-1 text-nexus-text-secondary hover:text-white"><CloseIcon className="w-6 h-6"/></button>
        </header>

        <main className="flex-grow p-6 overflow-y-auto prose prose-invert max-w-none prose-sm">
            <p className="text-nexus-text-secondary">Welcome to BW Nexus AI. By clicking "Accept and Continue," you agree to be bound by the following terms and conditions. Please read them carefully.</p>
            
            <h4>1. Service Description</h4>
            <p>The BW Nexus AI platform provides AI-powered intelligence, analysis, and report generation services for regional development and strategic partnership identification. The service is provided "as-is" and is intended for guidance and decision-support only.</p>

            <h4>2. User Responsibilities</h4>
            <p>You are responsible for the accuracy of the information you provide and for independently verifying any information generated by the system before making strategic or financial commitments. You agree not to use the service for any unlawful purpose.</p>
            
            <h4>3. Data and Privacy</h4>
            <p>We are committed to protecting your privacy. Information you provide is used solely for the purpose of generating your requested reports and improving our services. We do not sell your data to third parties. Please refer to our full Privacy Policy for more details.</p>

            <h4>4. Intellectual Property</h4>
            <p>The reports and content generated for you are for your internal use. The underlying technology, proprietary models (including but not limited to RROI, TPT, SEAM), and the BW Nexus AI platform itself are the exclusive intellectual property of BW Global Advisory.</p>

            <h4>5. Limitation of Liability</h4>
            <p>BW Global Advisory makes no warranties as to the absolute completeness or accuracy of the AI-generated content. In no event shall BW Global Advisory be liable for any direct, indirect, incidental, or consequential damages arising out of the use of or inability to use the service.</p>

            <p>By accepting, you acknowledge that you have read, understood, and agree to these terms.</p>
        </main>

        <footer className="p-4 border-t border-nexus-border-medium flex-shrink-0 flex justify-end items-center gap-4">
            <button onClick={onDecline} className="nexus-button-secondary">Decline</button>
            <button onClick={onAccept} className="nexus-button-primary">Accept</button>
        </footer>
      </div>
    </div>
  );
};